name: .NET CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Check code formatting
      run: dotnet format --verify-no-changes --verbosity detailed

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests and check coverage
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Threshold=50 /p:Exclude="[Pepsi.API]*"

    - name: Run .NET Code Analysis
      run: dotnet build /p:EnforceCodeStyleInBuild=true /p:AnalysisMode=All /p:TreatWarningsAsErrors=true
